import type {
  User,
  VoterRegistration,
  RegistrationDevice,
  DedupMatch,
  Exception,
  AuditLog,
  SystemStats,
  Province,
} from './types';

// Current user
export const currentUser: User = {
  id: 'usr-001',
  name: 'John Kamara',
  role: 'national_admin',
  clearanceLevel: 5,
  email: 'j.kamara@pngec.gov.pg',
  lastLogin: new Date('2026-01-25T08:30:00'),
};

// System statistics
export const systemStats: SystemStats = {
  totalRegistrations: 4827341,
  pendingSync: 12847,
  pendingDedup: 3421,
  activeDevices: 1847,
  offlineDevices: 234,
  exceptionsOpen: 891,
  duplicatesDetected: 4532,
  syncCompletionRate: 97.3,
};

// Mock voter registrations
export const mockVoterRegistrations: VoterRegistration[] = [
  {
    id: 'reg-001',
    voterId: 'PNG-2027-4521896',
    firstName: 'Michael',
    lastName: 'Toroama',
    dateOfBirth: new Date('1985-03-15'),
    gender: 'male',
    province: 'Eastern Highlands',
    district: 'Goroka',
    llg: 'Gahuku',
    ward: 'Asaro 1',
    pollingPlace: 'Asaro Primary School',
    villageLocality: 'Asaro Village',
    facialImageId: 'img-001',
    fingerprintTemplateIds: ['fp-001-l1', 'fp-001-l2', 'fp-001-r1', 'fp-001-r2'],
    gpsCoordinates: { latitude: -6.0821, longitude: 145.3861, accuracy: 5 },
    registrationTimestamp: new Date('2026-01-24T09:15:00'),
    deviceId: 'DEV-EHP-001',
    operatorId: 'OP-EHP-042',
    status: 'approved',
    dedupStatus: 'unique',
    signatureHash: 'sha256:abc123...',
    syncStatus: 'synced',
  },
  {
    id: 'reg-002',
    voterId: 'PNG-2027-4521897',
    firstName: 'Mary',
    lastName: 'Somare',
    dateOfBirth: new Date('1990-07-22'),
    gender: 'female',
    province: 'East Sepik',
    district: 'Wewak',
    llg: 'Wewak Islands',
    ward: 'Kairiru',
    pollingPlace: 'Kairiru Health Center',
    villageLocality: 'Shagur Village',
    facialImageId: 'img-002',
    fingerprintTemplateIds: ['fp-002-l1', 'fp-002-r1'],
    gpsCoordinates: { latitude: -3.5536, longitude: 143.6314, accuracy: 8 },
    registrationTimestamp: new Date('2026-01-24T10:30:00'),
    deviceId: 'DEV-ESP-003',
    operatorId: 'OP-ESP-015',
    status: 'pending_review',
    dedupStatus: 'pending',
    signatureHash: 'sha256:def456...',
    syncStatus: 'synced',
  },
  {
    id: 'reg-003',
    voterId: 'PNG-2027-4521898',
    firstName: 'Peter',
    lastName: 'Ipatas',
    dateOfBirth: new Date('1978-11-08'),
    gender: 'male',
    province: 'Enga',
    district: 'Wabag',
    llg: 'Wabag Urban',
    ward: 'Wabag Town',
    pollingPlace: 'Wabag Secondary School',
    villageLocality: 'Wabag Town',
    facialImageId: 'img-003',
    fingerprintTemplateIds: ['fp-003-l1', 'fp-003-l2', 'fp-003-r1', 'fp-003-r2'],
    gpsCoordinates: { latitude: -5.4897, longitude: 143.7189, accuracy: 3 },
    registrationTimestamp: new Date('2026-01-24T11:45:00'),
    deviceId: 'DEV-ENG-007',
    operatorId: 'OP-ENG-008',
    status: 'approved',
    dedupStatus: 'potential_duplicate',
    signatureHash: 'sha256:ghi789...',
    syncStatus: 'synced',
  },
];

// Mock devices
export const mockDevices: RegistrationDevice[] = [
  {
    id: 'DEV-NCD-001',
    deviceName: 'NCD Registration Kit 01',
    model: 'Samsung Galaxy Tab S8',
    serialNumber: 'SGT8-NCD-001',
    assignedWard: 'Moresby North-East',
    assignedOperator: 'Janet Ravu',
    status: 'online',
    lastSync: new Date('2026-01-25T10:45:00'),
    batteryLevel: 85,
    storageUsed: 12.4,
    storageTotal: 128,
    gpsEnabled: true,
    firmwareVersion: '2.1.4',
    registrationCount: 847,
  },
  {
    id: 'DEV-EHP-001',
    deviceName: 'EHP Registration Kit 01',
    model: 'Samsung Galaxy Tab S8',
    serialNumber: 'SGT8-EHP-001',
    assignedWard: 'Asaro 1',
    assignedOperator: 'Tom Wari',
    status: 'online',
    lastSync: new Date('2026-01-25T09:30:00'),
    batteryLevel: 72,
    storageUsed: 18.7,
    storageTotal: 128,
    gpsEnabled: true,
    firmwareVersion: '2.1.4',
    registrationCount: 1245,
  },
  {
    id: 'DEV-ESP-003',
    deviceName: 'ESP Registration Kit 03',
    model: 'Samsung Galaxy Tab S7',
    serialNumber: 'SGT7-ESP-003',
    assignedWard: 'Kairiru',
    assignedOperator: 'David Sana',
    status: 'offline',
    lastSync: new Date('2026-01-24T18:20:00'),
    batteryLevel: 15,
    storageUsed: 45.2,
    storageTotal: 64,
    gpsEnabled: true,
    firmwareVersion: '2.1.3',
    registrationCount: 523,
  },
  {
    id: 'DEV-WHP-002',
    deviceName: 'WHP Registration Kit 02',
    model: 'Samsung Galaxy Tab S8',
    serialNumber: 'SGT8-WHP-002',
    assignedWard: 'Kagamuga',
    assignedOperator: 'Lucy Kuman',
    status: 'degraded',
    lastSync: new Date('2026-01-25T08:15:00'),
    batteryLevel: 45,
    storageUsed: 89.3,
    storageTotal: 128,
    gpsEnabled: false,
    firmwareVersion: '2.1.2',
    registrationCount: 2103,
  },
];

// Mock dedup matches
export const mockDedupMatches: DedupMatch[] = [
  {
    id: 'match-001',
    voter1Id: 'PNG-2027-4521898',
    voter2Id: 'PNG-2027-3287456',
    matchScore: 94.7,
    matchType: 'fingerprint',
    status: 'pending_review',
  },
  {
    id: 'match-002',
    voter1Id: 'PNG-2027-4521234',
    voter2Id: 'PNG-2027-4521567',
    matchScore: 87.3,
    matchType: 'facial',
    status: 'pending_review',
  },
  {
    id: 'match-003',
    voter1Id: 'PNG-2027-4527891',
    voter2Id: 'PNG-2027-4521012',
    matchScore: 98.2,
    matchType: 'multi',
    status: 'confirmed_match',
    reviewedBy: 'usr-002',
    reviewedAt: new Date('2026-01-24T14:30:00'),
    decisionReason: 'Same person registered twice in different wards',
  },
];

// Mock exceptions
export const mockExceptions: Exception[] = [
  {
    id: 'exc-001',
    voterId: 'PNG-2027-4521456',
    exceptionType: 'missing_fingerprint',
    reasonCode: 'MF-01',
    description: 'Voter has no fingers on left hand due to industrial accident',
    status: 'under_review',
    createdBy: 'OP-EHP-042',
    createdAt: new Date('2026-01-24T11:00:00'),
  },
  {
    id: 'exc-002',
    voterId: 'PNG-2027-4521789',
    exceptionType: 'worn_fingerprint',
    reasonCode: 'WF-01',
    description: 'Elderly voter with severely worn fingerprints - agricultural worker',
    status: 'approved',
    createdBy: 'OP-WHP-015',
    createdAt: new Date('2026-01-23T09:30:00'),
    reviewedBy: 'usr-003',
    reviewedAt: new Date('2026-01-23T14:45:00'),
    supervisorOverride: {
      supervisorId: 'usr-003',
      reasonCode: 'SO-WF-01',
      justification: 'Alternative biometric (facial + iris) captured. Verified by community leader.',
      timestamp: new Date('2026-01-23T14:45:00'),
    },
  },
  {
    id: 'exc-003',
    voterId: 'PNG-2027-4521999',
    exceptionType: 'disability_accommodation',
    reasonCode: 'DA-02',
    description: 'Voter is visually impaired, requires assisted registration',
    status: 'open',
    createdBy: 'OP-SHP-008',
    createdAt: new Date('2026-01-25T08:15:00'),
  },
];

// Mock audit logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'aud-001',
    timestamp: new Date('2026-01-25T10:45:32'),
    action: 'REGISTRATION_CREATED',
    entityType: 'voter_registration',
    entityId: 'reg-001',
    userId: 'OP-EHP-042',
    userRole: 'registration_officer',
    signature: 'sha256:sig001...',
    deviceId: 'DEV-EHP-001',
  },
  {
    id: 'aud-002',
    timestamp: new Date('2026-01-25T10:46:15'),
    action: 'BIOMETRIC_CAPTURED',
    entityType: 'fingerprint_template',
    entityId: 'fp-001-l1',
    userId: 'OP-EHP-042',
    userRole: 'registration_officer',
    signature: 'sha256:sig002...',
    deviceId: 'DEV-EHP-001',
  },
  {
    id: 'aud-003',
    timestamp: new Date('2026-01-25T11:00:00'),
    action: 'SYNC_COMPLETED',
    entityType: 'device',
    entityId: 'DEV-EHP-001',
    userId: 'SYSTEM',
    userRole: 'ict_security',
    oldValue: 'pending',
    newValue: 'synced',
    signature: 'sha256:sig003...',
  },
  {
    id: 'aud-004',
    timestamp: new Date('2026-01-25T11:15:00'),
    action: 'DEDUP_MATCH_DETECTED',
    entityType: 'dedup_match',
    entityId: 'match-001',
    userId: 'SYSTEM',
    userRole: 'ict_security',
    signature: 'sha256:sig004...',
  },
  {
    id: 'aud-005',
    timestamp: new Date('2026-01-25T11:30:00'),
    action: 'EXCEPTION_APPROVED',
    entityType: 'exception',
    entityId: 'exc-002',
    userId: 'usr-003',
    userRole: 'supervisor',
    oldValue: 'under_review',
    newValue: 'approved',
    signature: 'sha256:sig005...',
  },
];

// Mock provinces (partial for demonstration)
export const mockProvinces: Province[] = [
  {
    code: 'NCD',
    name: 'National Capital District',
    districts: [
      {
        code: 'NCD-MNW',
        name: 'Moresby North-West',
        provinceCode: 'NCD',
        llgs: [],
      },
      {
        code: 'NCD-MNE',
        name: 'Moresby North-East',
        provinceCode: 'NCD',
        llgs: [],
      },
      {
        code: 'NCD-MS',
        name: 'Moresby South',
        provinceCode: 'NCD',
        llgs: [],
      },
    ],
  },
  {
    code: 'EHP',
    name: 'Eastern Highlands',
    districts: [
      {
        code: 'EHP-GOR',
        name: 'Goroka',
        provinceCode: 'EHP',
        llgs: [],
      },
      {
        code: 'EHP-KAI',
        name: 'Kainantu',
        provinceCode: 'EHP',
        llgs: [],
      },
    ],
  },
  {
    code: 'WHP',
    name: 'Western Highlands',
    districts: [
      {
        code: 'WHP-HAG',
        name: 'Hagen',
        provinceCode: 'WHP',
        llgs: [],
      },
    ],
  },
  {
    code: 'ESP',
    name: 'East Sepik',
    districts: [
      {
        code: 'ESP-WEW',
        name: 'Wewak',
        provinceCode: 'ESP',
        llgs: [],
      },
    ],
  },
  {
    code: 'ENG',
    name: 'Enga',
    districts: [
      {
        code: 'ENG-WAB',
        name: 'Wabag',
        provinceCode: 'ENG',
        llgs: [],
      },
    ],
  },
];

// Recent activity for dashboard
export const recentActivity = [
  { time: '10:45', action: 'Batch sync completed', location: 'Eastern Highlands', count: 847 },
  { time: '10:42', action: 'New exception raised', location: 'Western Highlands', count: 1 },
  { time: '10:38', action: 'Duplicate confirmed', location: 'Enga', count: 1 },
  { time: '10:35', action: 'Device went offline', location: 'East Sepik', count: 1 },
  { time: '10:30', action: 'Batch sync completed', location: 'NCD', count: 523 },
  { time: '10:28', action: 'Exception approved', location: 'Morobe', count: 1 },
  { time: '10:25', action: 'Registrations uploaded', location: 'Simbu', count: 234 },
];

// Province registration stats
export const provinceStats = [
  { province: 'Eastern Highlands', registered: 412847, target: 500000, syncRate: 98.2 },
  { province: 'Western Highlands', registered: 389421, target: 450000, syncRate: 96.8 },
  { province: 'NCD', registered: 287654, target: 320000, syncRate: 99.1 },
  { province: 'Morobe', registered: 456123, target: 550000, syncRate: 94.5 },
  { province: 'East Sepik', registered: 234567, target: 300000, syncRate: 92.3 },
  { province: 'Enga', registered: 198765, target: 250000, syncRate: 97.4 },
  { province: 'Simbu', registered: 176543, target: 200000, syncRate: 95.8 },
  { province: 'Southern Highlands', registered: 312456, target: 400000, syncRate: 93.2 },
];
